# Servicio de desarrollo para el proyecto Angular
services:
  # Servicio de desarrollo - Angular con hot reload
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      # Montar código fuente para hot reload
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend-network

# Red personalizada para comunicación entre servicios
networks:
  frontend-network:
    driver: bridge
    name: angular-frontend-network

# Volúmenes para persistencia de datos
volumes:
  node_modules:
    driver: local 